#coding:UTF-8

DATABASE = 'mmp.db'

# User type
STUDENT = 1
STAFF = 2

CREATE = 9
COMMIT = 8

# Task action
ALREADY = 0
RECEIVED = 1
COMPLETE = 2
CALL = 3
FAILED = -1
ABORT = -2

# Task statu
OPEN = 0
CLOSED = 1

CLOSED_STR = "CLOSED"
ALREADY_STR = 'ALREADY'
RECEIVED_STR = 'RECEIVED'
COMPLETE_STR = 'COMPLETE'
ABORT_STR = "ABORT"
FAILED_STR = 'FAILED'
COMMIT_STR = "COMMIT"
CALL_STR = "CALL"
TASK_STATU_LABELS = [ALREADY_STR, RECEIVED_STR, COMPLETE_STR, CALL_STR, 0, 0, 0, 0, COMMIT_STR, 0, 0, ABORT_STR, FAILED_STR]

# # TUb statu
# RECEIVED = 0
# COMPLETE = 1
# COMMIT = 2
# ABORT = -1

# event statu
CHECKED = 0
RAISED = 1

CHECK_SPACE = 20
